version: '3.8'

services:
  metasploitable2:
    image: tleemcjr/metasploitable2
    container_name: metasploitable2
    hostname: victim
    networks:
      - pentest
    tty: true
    stdin_open: true

  kali:
    build: .
    container_name: kalibox
    hostname: attacker
    networks:
      - pentest
    tty: true
    stdin_open: true

networks:
  pentest:
    driver: bridge
